In [2]:
import pandas as pd

# Análise Final - Sample Superstore

## 1. Carregamento da base tratada

In [3]:
def carregar_dados(caminho):
    dados=pd.read_csv(caminho,encoding='utf-8',parse_dates=['Order Date', 'Ship Date'])
    return dados

In [4]:
caminho='../dados/tratado/superstore_tratado.csv'
df=carregar_dados(caminho)

In [5]:
print(f'quantidade de linhas {len(df)}')
print(f'quantidade de colunas {len(df.columns)}')

quantidade de linhas 9994
quantidade de colunas 26

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          9994 non-null   int64
 1   Order ID        9994 non-null   str
 2   Order Date      9994 non-null   datetime64[us]
 3   Ship Date       9994 non-null   datetime64[us]
 4   Ship Mode       9994 non-null   str
 5   Customer ID     9994 non-null   str
 6   Customer Name   9994 non-null   str
 7   Segment         9994 non-null   str
 8   Country         9994 non-null   str
 9   City            9994 non-null   str
 10  State           9994 non-null   str
 11  Postal Code     9994 non-null   int64
 12  Region          9994 non-null   str
 13  Product ID      9994 non-null   str
 14  Category        9994 non-null   str
 15  Sub-Category    9994 non-null   str
 16  Product Name    9994 non-null   str
 17  Sales           9994 non-null   float64
 18  Quantity        9994 non-null   int64
 19  Discount        9994 non-null   float64
 20  Profit          9994 non-null   float64
 21  dias_envio      9994 non-null   int64
 22  ano             9994 non-null   int64
 23  mes             9994 non-null   int64
 24  margem_lucro    9994 non-null   float64
 25  faixa_desconto  9994 non-null   str
dtypes: datetime64[us](2), float64(4), int64(6), str(14)
memory usage: 3.7 MB

In [7]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,dias_envio,ano,mes,margem_lucro,faixa_desconto
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3,2016,11,0.1600,sem desconto
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3,2016,11,0.3000,sem desconto
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4,2016,6,0.4700,sem desconto
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7,2015,10,-0.4000,desconto agressivo
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7,2015,10,0.1125,desconto alto

## 2. Validação da base tratada

Nesta etapa, verificamos se a base gerada pelo processo de limpeza está pronta para a análise.

In [8]:
nulo=df.isnull().sum()
print(f'Dados nulos por coluna:{nulo}')

Dados nulos por coluna:Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dias_envio        0
ano               0
mes               0
margem_lucro      0
faixa_desconto    0
dtype: int64

In [9]:
duplicado=df.duplicated().sum()
print(f'Linhas duplicadas: {duplicado}')

Linhas duplicadas: 0

In [10]:
data_inicial=df['Order Date'].min()
data_final=df['Order Date'].max()
print(f'menor data pedido:{data_inicial}')
print(f'maior data pedido:{data_final}')

menor data pedido:2014-01-03 00:00:00
maior data pedido:2017-12-30 00:00:00

In [11]:
desconto=df['Discount']
minimodesconto=desconto.min()
maximodesconto=desconto.max()
print(f'menor desconto:{minimodesconto}')
print(f'maior desconto:{maximodesconto}')

menor desconto:0.0
maior desconto:0.8

In [12]:
prazo_envio=df['dias_envio']
prazominimo=prazo_envio.min()
prazomaximo=prazo_envio.max()
print(f'menor prazo de envio:{prazominimo}')
print(f'maior prazo de envio:{prazomaximo}')

menor prazo de envio:0
maior prazo de envio:7

In [13]:
anos=df['ano']
listaanos=sorted(set(anos))
for i in listaanos:
    print(i)

2014
2015
2016
2017

In [14]:
faixadesconto=df['faixa_desconto']
listadesconto=set(faixadesconto)
for i in listadesconto:
    print(i)

desconto agressivo
sem desconto
desconto baixo
desconto alto

## 3. Visão geral do negócio

In [15]:
def calcular_kpis(dados):
    faturamento=dados['Sales'].sum()
    lucrototal=dados['Profit'].sum()
    margemglobal=lucrototal/faturamento
    quantidadevendida=dados['Quantity'].sum()
    totalpedidos=dados['Order ID'].nunique()
    ticketmedio=faturamento/totalpedidos

    kpis={
    'faturamento_total': faturamento,
    'lucro_total': lucrototal,
    'margem_global': margemglobal,
    'quantidade_vendida': quantidadevendida,
    'total_pedidos': totalpedidos,
    'ticket_medio': ticketmedio
    }

    return kpis

In [16]:
kpis=calcular_kpis(df)

print(f"Faturamento total: US$ {kpis['faturamento_total']:.2f}")
print(f"Lucro total: US$ {kpis['lucro_total']:.2f}")
print(f"Margem global: {kpis['margem_global']:.2%}")
print(f"Quantidade vendida: {kpis['quantidade_vendida']:}")
print(f"Total de pedidos: {kpis['total_pedidos']:}")
print(f"Ticket médio: US$ {kpis['ticket_medio']:.2f}")

Faturamento total: US$ 2297200.86
Lucro total: US$ 286397.02
Margem global: 12.47%
Quantidade vendida: 37873
Total de pedidos: 5009
Ticket médio: US$ 458.61

### Interpretação dos KPIs

A empresa apresentou lucro no período analisado. O faturamento foi de aproximadamente US$ 2.30 milhões, com lucro total de US$ 286,40 mil.

A margem global foi de 12,47%. Isso significa que, para cada US$ 100 faturados, aproximadamente US$ 12,47 permaneceram como lucro.

O ticket médio foi de US$ 458,61. Isso representa o valor médio faturado por pedido, considerando os 5.009 pedidos únicos registrados na base.

Apesar do resultado geral positivo, ainda é necessário investigar se existem categorias, regiões ou períodos com baixa lucratividade ou prejuízo assim como foi feito na exploração inicial onde achamos categorias com prejuizo.

## 4. Análise temporal

### 4.1 Desempenho anual

In [17]:
def resumir_por_grupo(dados, coluna_grupo):
    resumo=dados.groupby(coluna_grupo).agg(
        faturamento_total=('Sales','sum'),
        lucro_total=('Profit','sum'),
        quantidade_vendida=('Quantity','sum'),
        total_pedidos=('Order ID','nunique'),
    )
    resumo['margem_global']=(
        resumo['lucro_total']/resumo['faturamento_total']
    )
    resumo['ticket_medio']=(
        resumo['faturamento_total']/resumo['total_pedidos']
    )
    return resumo

def variacoes_temporais(resumo):
    resumo_temporal=resumo.copy()
    resumo_temporal['variacao_faturamento']=(
        resumo_temporal['faturamento_total'].pct_change()
    )
    resumo_temporal['variacao_lucro']=(
        resumo_temporal['lucro_total'].pct_change()
    )
    return resumo_temporal

resumo_anual_base=resumir_por_grupo(df, 'ano')
resumo_anual=variacoes_temporais(resumo_anual_base)
resumo_anual

,faturamento_total,lucro_total,quantidade_vendida,total_pedidos,margem_global,ticket_medio,variacao_faturamento,variacao_lucro
ano,,,,,,,,
2014,484247.4981,49543.9741,7581,969,0.102311,499.739420,NaN,NaN
2015,470532.5090,61618.6037,7979,1038,0.130955,453.306849,-0.028322,0.243715
2016,609205.5980,81795.1743,9837,1315,0.134265,463.274219,0.294715,0.327443
2017,733215.2552,93439.2696,12476,1687,0.127438,434.626707,0.203560,0.142357

### Interpretação do resumo anual

O ano de 2016 apresentou a maior margem global, com 13,43%, enquanto 2014 teve a menor margem, com 10,23%.

Em 2015, o faturamento foi menor do que em 2014. Mesmo assim, o lucro aumentou e a margem passou de 10,23% para 13,10%. Isso indica uma melhora na eficiência financeira das vendas realizadas naquele ano.

Ainda é necessário investigar quais fatores contribuíram para essa melhora, como descontos, categorias vendidas ou desempenho regional.

A quantidade vendida aumentou em todos os anos. Em 2015, foram vendidas mais unidades do que em 2014, mas o faturamento foi o menor de todo o período analisado.

Isso indica que o aumento no volume de produtos vendidos não resultou em crescimento do faturamento. Uma possível explicação é a venda de produtos com menor valor médio ou uma mudança no comportamento dos descontos, hipóteses que ainda precisam ser investigadas.

O ticket médio caiu de US$ 499,74 em 2014 para US$ 453,31 em 2015. Isso reforça a conclusão de que, apesar do aumento no número de pedidos e na quantidade vendida, cada pedido gerou menos faturamento em média.

Em 2017, o ticket médio foi ainda menor, com US$ 434,63. Mesmo assim, o ano apresentou o maior faturamento do período, sustentado pelo aumento expressivo no número de pedidos e na quantidade vendida.

Esses resultados mostram que o crescimento do faturamento pode vir do aumento do volume de pedidos, mesmo quando o valor médio de cada pedido diminui.

variação faturamento:
2015: queda de 2,83%
2016: crescimento de 29,47%
2017: crescimento de 20,36%

variação de lucro:
2015: crescimento de 24,37%
2016: crescimento de 32,74%
2017: crescimento de 14,24%

Em 2015, o faturamento caiu 2,83%, mas o lucro cresceu 24,37%. Esse contraste reforça que houve melhora na eficiência financeira, embora a causa ainda precise ser investigada.

Em 2016, o lucro cresceu 32,74%, superando o crescimento de 29,47% do faturamento. Como o lucro avançou mais rapidamente, a margem global aumentou.

Em 2017, o faturamento cresceu 20,36%, enquanto o lucro cresceu apenas 14,24%. Como o lucro avançou mais lentamente que o faturamento, a margem global diminuiu.

In [18]:
formatacao_resumo={
    'faturamento_total': 'US$ {:,.2f}',
    'lucro_total': 'US$ {:,.2f}',
    'quantidade_vendida': '{:,.0f}',
    'total_pedidos': '{:,.0f}',
    'margem_global': '{:.2%}',
    'ticket_medio': 'US$ {:,.2f}',
    'variacao_faturamento': '{:.2%}',
    'variacao_lucro': '{:.2%}'
}


resumo_anual_formatado=resumo_anual.style.format(
    formatacao_resumo,
    na_rep='-',
    decimal=',',
    thousands='.'
)


resumo_anual_formatado

### 4.2 Desempenho mensal

In [19]:
resumo_mensal_base=resumir_por_grupo(
    df,
    ['ano','mes']
)

resumo_mensal_base

resumo_mensal=resumo_mensal_base.copy()
resumo_mensal['variacao_faturamento']=(
    resumo_mensal['faturamento_total'].pct_change()
)

resumo_mensal['diferenca_lucro']=(
    resumo_mensal['lucro_total'].diff()
)

resumo_mensal

          faturamento_total  lucro_total  quantidade_vendida  total_pedidos  \
ano  mes
2014 1           14236.8950    2450.1907                 284             32
     2            4519.8920     862.3084                 159             28
     3           55691.0090     498.7299                 585             71
     4           28295.3450    3488.8352                 536             66
     5           23648.2870    2738.7096                 466             69
     6           34595.1276    4976.5244                 521             66
     7           33946.3930    -841.4826                 550             65
     8           27909.4685    5318.1050                 609             72
     9           81777.3508    8328.0994                1000            130
     10          31453.3930    3448.2573                 573             78
     11          78628.7167    9292.1269                1219            151
     12          69545.6205    8983.5699                1079            141
2015 1           18174.0756   -3281.0070                 236             29
     2           11951.4110    2813.8508                 239             36
     3           38726.2520    9732.0978                 515             79
     4           34195.2085    4187.4962                 543             72
     5           30131.6865    4667.8690                 575             74
     6           24797.2920    3335.5572                 486             68
     7           28765.3250    3288.6483                 557             66
     8           36898.3322    5355.8084                 598             68
     9           64595.9180    8209.1627                1086            140
     10          31404.9235    2817.3660                 631             87
     11          75972.5635   12474.7884                1310            158
     12          74919.5212    8016.9659                1203            161
2016 1           18542.4910    2824.8233                 358             48
     2           22978.8150    5004.5795                 306             45
     3           51715.8750    3611.9680                 579             86
     4           38750.0390    2977.8149                 635             89
     5           56987.7280    8662.1464                 863            108
     6           40344.5340    4750.3781                 742             97
     7           39261.9630    4432.8779                 758             96
     8           31115.3743    2062.0693                 693             90
     9           73410.0249    9328.6576                1316            192
     10          59687.7450   16243.1425                 767            105
     11          79411.9658    4011.4075                1406            183
     12          96999.0430   17885.3093                1414            176
2017 1           43971.3740    7140.4391                 597             69
     2           20301.1334    1613.8720                 363             53
     3           58872.3528   14751.8915                 885            118
     4           36521.5361     933.2900                 733            116
     5           44261.1102    6342.5828                 887            118
     6           52981.7257    8223.3357                 931            133
     7           45264.4160    6952.6212                 840            111
     8           63120.8880    9040.9557                 884            111
     9           87866.6520   10991.5556                1660            226
     10          77776.9232    9275.2755                1133            147
     11         118447.8250    9690.1037                1840            261
     12          83829.3188    8483.3468                1723            224

          margem_global  ticket_medio  variacao_faturamento  diferenca_lucro
ano  mes
2014 1         0.172101    444.902969                   NaN              NaN
     2         0.190781    161.424714             -0.682523       -1587.8823
     3         0.008955    784.380408             11.321314        -363.5785
     4         0.123301    428.717348             -0.491923        2990.1053
     5         0.115810    342.728797             -0.164234        -750.1256
     6         0.143850    524.168600              0.462902        2237.8148
     7        -0.024789    522.252200             -0.018752       -5818.0070
     8         0.190548    387.631507             -0.177837        6159.5876
     9         0.101839    629.056545              1.930093        3009.9944
     10        0.109631    403.248628             -0.615378       -4879.8421
     11        0.118177    520.719978              1.499848        5843.8696
     12        0.129175    493.231351             -0.115519        -308.5570
2015 1        -0.180532    626.692262             -0.738674      -12264.5769
     2         0.235441    331.983639             -0.342392        6094.8578
     3         0.251305    490.205722              2.240308        6918.2470
     4         0.122459    474.933451             -0.117002       -5544.6016
     5         0.154916    407.184953             -0.118833         480.3728
     6         0.134513    364.666059             -0.177036       -1332.3118
     7         0.114327    435.838258              0.160019         -46.9089
     8         0.145150    542.622532              0.282736        2067.1601
     9         0.127085    461.399414              0.750646        2853.3543
     10        0.089711    360.976132             -0.513825       -5391.7967
     11        0.164201    480.839009              1.419129        9657.4224
     12        0.107008    465.338641             -0.013861       -4457.8225
2016 1         0.152343    386.301896             -0.752501       -5192.1426
     2         0.217791    510.640333              0.239252        2179.7562
     3         0.069843    601.347384              1.250589       -1392.6115
     4         0.076847    435.393697             -0.250713        -634.1531
     5         0.152000    527.664148              0.470650        5684.3315
     6         0.117745    415.923031             -0.292049       -3911.7683
     7         0.112905    408.978781             -0.026833        -317.5002
     8         0.066272    345.726381             -0.207493       -2370.8086
     9         0.127076    382.343880              1.359285        7266.5883
     10        0.272135    568.454714             -0.186927        6914.4849
     11        0.050514    433.945168              0.330457      -12231.7350
     12        0.184386    551.130926              0.221466       13873.9018
2017 1         0.162388    637.266290             -0.546682      -10744.8702
     2         0.079497    383.040253             -0.538310       -5526.5671
     3         0.250574    498.918244              1.899954       13138.0195
     4         0.025555    314.840828             -0.379649      -13818.6015
     5         0.143299    375.094154              0.211918        5409.2928
     6         0.155211    398.358840              0.197027        1880.7529
     7         0.153600    407.787532             -0.145660       -1270.7145
     8         0.143232    568.656649              0.394492        2088.3345
     9         0.125094    388.790496              0.392038        1950.5999
     10        0.119255    529.094716             -0.114830       -1716.2801
     11        0.081809    453.823084              0.522917         414.8282
     12        0.101198    374.238030             -0.292268       -1206.7569

In [20]:
formatacao_resumo_mensal={
    'faturamento_total': 'US$ {:,.2f}',
    'lucro_total': 'US$ {:,.2f}',
    'quantidade_vendida': '{:,.0f}',
    'total_pedidos': '{:,.0f}',
    'margem_global': '{:.2%}',
    'ticket_medio': 'US$ {:,.2f}',
    'variacao_faturamento': '{:.2%}',
    'diferenca_lucro': 'US$ {:,.2f}'
}

resumo_mensal_formatado=resumo_mensal.style.format(
    formatacao_resumo_mensal,
    na_rep='-',
    decimal=',',
    thousands='.'
)

resumo_mensal_formatado

In [21]:
meses_prejuizo=resumo_mensal[
    resumo_mensal['lucro_total']<0
]

meses_prejuizo

,,faturamento_total,lucro_total,quantidade_vendida,total_pedidos,margem_global,ticket_medio,variacao_faturamento,diferenca_lucro
ano,mes,,,,,,,,
2014,7,33946.3930,-841.4826,550,65,-0.024789,522.252200,-0.018752,-5818.0070
2015,1,18174.0756,-3281.0070,236,29,-0.180532,626.692262,-0.738674,-12264.5769

#### Meses com prejuízo

Janeiro de 2015 apresentou o maior prejuízo, com aproximadamente US$ 3.281,01 negativos, e também a pior margem global, com -18,05%.

Apesar de seu ticket médio de US$ 626,69 ser maior que o de julho de 2014, janeiro de 2015 teve menos pedidos, menor quantidade vendida e um prejuízo mais elevado.

Isso mostra que analisar somente o ticket médio não é suficiente. Um pedido pode apresentar valor médio alto e ainda gerar prejuízo. Para avaliar o desempenho, é necessário observar também o lucro e a margem global.

In [22]:
ranking_lucro_mensal=resumo_mensal.sort_values(['lucro_total'])
ranking_lucro_mensal.head()

          faturamento_total  lucro_total  quantidade_vendida  total_pedidos  \
ano  mes
2015 1           18174.0756   -3281.0070                 236             29
2014 7           33946.3930    -841.4826                 550             65
     3           55691.0090     498.7299                 585             71
     2            4519.8920     862.3084                 159             28
2017 4           36521.5361     933.2900                 733            116

          margem_global  ticket_medio  variacao_faturamento  diferenca_lucro
ano  mes
2015 1        -0.180532    626.692262             -0.738674      -12264.5769
2014 7        -0.024789    522.252200             -0.018752       -5818.0070
     3         0.008955    784.380408             11.321314        -363.5785
     2         0.190781    161.424714             -0.682523       -1587.8823
2017 4         0.025555    314.840828             -0.379649      -13818.6015

In [23]:
ranking_margem_global=resumo_mensal.sort_values(['margem_global'])
ranking_margem_global.head()

          faturamento_total  lucro_total  quantidade_vendida  total_pedidos  \
ano  mes
2015 1           18174.0756   -3281.0070                 236             29
2014 7           33946.3930    -841.4826                 550             65
     3           55691.0090     498.7299                 585             71
2017 4           36521.5361     933.2900                 733            116
2016 11          79411.9658    4011.4075                1406            183

          margem_global  ticket_medio  variacao_faturamento  diferenca_lucro
ano  mes
2015 1        -0.180532    626.692262             -0.738674      -12264.5769
2014 7        -0.024789    522.252200             -0.018752       -5818.0070
     3         0.008955    784.380408             11.321314        -363.5785
2017 4         0.025555    314.840828             -0.379649      -13818.6015
2016 11        0.050514    433.945168              0.330457      -12231.7350

### Interpretação dos rankings

Os rankings de lucro e margem são parecidos, mas respondem perguntas diferentes. Fevereiro de 2014 teve lucro total baixo principalmente por seu baixo volume de vendas, enquanto sua margem de 19,08% indica boa eficiência.

Novembro de 2016 apresentou faturamento elevado, mas margem de apenas 5,05%. Isso indica que um volume financeiro relevante gerou proporcionalmente pouco lucro.

Janeiro de 2015 continua sendo o mês mais crítico, pois combina o maior prejuízo com a pior margem global.

## 5. Categorias e subcategorias

In [33]:
formatacao_grupos={
    'faturamento_total': 'US$ {:,.2f}',
    'lucro_total': 'US$ {:,.2f}',
    'quantidade_vendida': '{:,.0f}',
    'total_pedidos': '{:,.0f}',
    'margem_global': '{:.2%}',
    'ticket_medio': 'US$ {:,.2f}'
}

In [35]:
resumo_categoria=resumir_por_grupo(df,'Category')

resumo_categoria_formatado=resumo_categoria.style.format(
    formatacao_grupos,
    na_rep='-',
    decimal=',',
    thousands='.'
)

resumo_categoria_formatado

### Interpretação por categoria

Technology apresentou o maior faturamento e o maior lucro, além da melhor margem global entre as categorias.

Furniture teve faturamento superior ao de Office Supplies, mas gerou muito menos lucro. Sua margem de apenas 2,49%, comparada a 17,04% de Office Supplies, indica baixa eficiência financeira.

Embora Furniture seja lucrativa no resultado total, a categoria provavelmente contém subcategorias que reduzem fortemente seu desempenho.

In [36]:
resumo_subcategoria=resumir_por_grupo(df,'Sub-Category')

resumo_subcategoria_formatado=resumo_subcategoria.style.format(
    formatacao_grupos,
    na_rep='-',
    decimal=',',
    thousands='.'
)

resumo_subcategoria_formatado

### Interpretação por subcategoria

Tables é a principal causa da baixa eficiência financeira de Furniture, enquanto Bookcases também contribui negativamente. Chairs e Furnishings evitam que a categoria termine com prejuízo, mas não são suficientes para produzir uma margem alta.

In [46]:
resumo_ano_categoria=resumir_por_grupo(df,['ano','Category'])

resumo_ano_categoria_2014_2015=resumo_ano_categoria.loc[[2014, 2015]]

resumo_ano_categoria_formatado=resumo_ano_categoria_2014_2015.style.format(
    formatacao_grupos,
    na_rep='-',
    decimal=',',
    thousands='.'
)

resumo_ano_categoria_formatado

### Comparação entre 2014 e 2015 por categoria

Technology foi a principal categoria associada à melhora da margem global em 2015. Mesmo com redução do faturamento, a categoria gerou aproximadamente US$ 12 mil a mais de lucro e aumentou sua margem em 8,32 pontos percentuais. Office Supplies também contribuiu positivamente, enquanto Furniture reduziu parte desse ganho.

In [55]:
technology=df[df['Category']=='Technology']

In [56]:
resumo_technology=resumir_por_grupo(technology,['ano', 'Sub-Category'])

resumo_technology_2014_2015=resumo_technology.loc[[2014,2015]]

resumo_technology_formatado=resumo_technology_2014_2015.style.format(
    formatacao_grupos,
    na_rep='-',
    decimal=',',
    thousands='.'
)
resumo_technology_formatado

### Comparação das subcategorias de Technology entre 2014 e 2015

A melhora de Technology em 2015 foi impulsionada principalmente por Copiers, que apresentou o maior aumento de lucro e margem. Machines também teve uma melhora relevante de eficiência, enquanto Accessories aumentou o lucro principalmente pelo crescimento do faturamento. Phones apresentou redução de lucro e não contribuiu para a melhora da categoria.

## 6. Análise dos descontos

### Comparação das faixas de desconto entre 2014 e 2015

In [48]:
resumo_faixa_desconto=resumir_por_grupo(technology,['ano', 'faixa_desconto'])

resumo_faixa_desconto_2014_2015=resumo_faixa_desconto.loc[[2014,2015]]

resumo_faixa_desconto_formatado=resumo_faixa_desconto_2014_2015.style.format(
    formatacao_grupos,
    na_rep='-',
    decimal=',',
    thousands='.'
)

resumo_faixa_desconto_formatado

### Interpretação das faixas de desconto

As vendas com desconto agressivo apresentaram faturamento menor e menor volume, mas geraram lucro e margem global negativos nos dois anos. Isso mostra que, apesar de ocorrerem com menor frequência, tiveram impacto financeiro relevante.

Os descontos altos, por outro lado, apresentaram lucro e margem positivos. Em 2015, essa faixa aumentou o lucro e melhorou a margem global, indicando que nem todo desconto foi prejudicial.

A melhora de Technology em 2015 parece estar associada ao crescimento das vendas sem desconto e à maior eficiência das vendas com desconto alto. Os descontos agressivos continuaram sendo um grupo problemático.

In [54]:
resumo_2014=resumo_faixa_desconto.loc[2014]
resumo_2015=resumo_faixa_desconto.loc[2015]
diferencas_desconto=pd.DataFrame({
    'diferenca_faturamento':(
        resumo_2015['faturamento_total']-resumo_2014['faturamento_total']
    ),

    'diferenca_lucro':(
        resumo_2015['lucro_total']-resumo_2014['lucro_total']
    ),

    'aumento_margem_pontos_percentuais':(
        resumo_2015['margem_global']-resumo_2014['margem_global']
    )*100,

    'diferenca_pedidos':(
        resumo_2015['total_pedidos']-resumo_2014['total_pedidos']
    )
})

formatacao_diferencas={
    'diferenca_faturamento': 'US$ {:,.2f}',
    'diferenca_lucro': 'US$ {:,.2f}',
    'aumento_margem_pontos_percentuais':('{:,.2f} pontos percentuais'),
    'diferenca_pedidos': '{:,.0f}',
}

diferencas_formatado=diferencas_desconto.style.format(
    formatacao_diferencas,
    na_rep='-',
    decimal=',',
    thousands='.'
)

diferencas_formatado

### Interpretação das diferenças de desconto

A melhora do lucro de Technology em 2015 foi impulsionada principalmente pelo crescimento das vendas sem desconto, que apresentaram o maior aumento de lucro.

As vendas com desconto alto também contribuíram, pois aumentaram o lucro e melhoraram a margem mesmo com menor faturamento.

Os descontos agressivos continuaram sendo prejudiciais. Apesar da redução do volume financeiro dessa faixa, ela permaneceu com lucro e margem negativos.

Portanto, a melhora de Technology está associada ao crescimento das vendas sem desconto e à maior eficiência dos descontos altos, e não a uma melhora das vendas com descontos agressivos.

## 7. Análise regional e por segmento

In [43]:
resumo_regiao=resumir_por_grupo(df,'Region')

resumo_regiao_formatado=resumo_regiao.style.format(
    formatacao_grupos,
    na_rep='-',
    decimal=',',
    thousands='.'
)

resumo_regiao_formatado

### Interpretação por região

West apresentou o melhor desempenho regional. Central, apesar de faturar mais que South, gerou menos lucro e teve a menor margem, indicando baixa eficiência financeira em comparação com as demais regiões.

In [44]:
resumo_segmento=resumir_por_grupo(df,'Segment')

resumo_segmento_formatado=resumo_segmento.style.format(
    formatacao_grupos,
    na_rep='-',
    decimal=',',
    thousands='.'
)

resumo_segmento_formatado

### Interpretação por segmento

Consumer apresentou o maior faturamento, lucro e volume de vendas, mas teve a menor margem entre os segmentos. Home Office, apesar do menor faturamento e lucro total, apresentou a melhor margem global e o maior ticket médio, indicando maior eficiência financeira.

## 8. Conclusão executiva

A empresa apresentou resultado acumulado positivo entre 2014 e 2017, com faturamento aproximado de US$ 2,30 milhões, lucro de US$ 286,40 mil e margem global de 12,47%. O lucro cresceu em todos os anos, mas o comportamento do faturamento e da margem mostrou que crescimento de volume não significa automaticamente maior eficiência.

Em 2015, o faturamento caiu 2,83%, enquanto o lucro aumentou 24,37% e a margem passou de 10,23% para 13,10%. A investigação associou essa melhora principalmente a Technology, especialmente Copiers. Dentro da categoria, o crescimento das vendas sem desconto e a maior eficiência das vendas com desconto alto foram os principais componentes positivos. Os descontos agressivos permaneceram com lucro e margem negativos.

Na análise de produtos, Technology apresentou o maior faturamento, lucro e margem global. Furniture, embora tenha faturado mais que Office Supplies, apresentou margem de apenas 2,49%. Tables foi a principal causa dessa baixa eficiência, com contribuição negativa adicional de Bookcases.

A análise mensal identificou prejuízo em julho de 2014 e janeiro de 2015. Janeiro de 2015 foi o período mais crítico, combinando o maior prejuízo com a pior margem global. O resultado mostrou que ticket médio elevado não garante lucratividade.

Regionalmente, West apresentou o melhor desempenho em faturamento, lucro e margem. Central teve a menor margem e, mesmo faturando mais que South, gerou menos lucro, indicando menor eficiência financeira.

Entre os segmentos, Consumer concentrou o maior faturamento, lucro e volume de vendas, mas apresentou a menor margem. Home Office teve menor resultado absoluto, porém alcançou a melhor margem global e o maior ticket médio, destacando-se pela eficiência.

### Recomendações de negócio

- Revisar a política de descontos agressivos, que apresentou impacto financeiro negativo.
- Investigar preços, custos e descontos de Tables e Bookcases para reduzir as perdas de Furniture.
- Avaliar os fatores que reduzem a eficiência da região Central.
- Preservar e estudar as práticas associadas ao desempenho de Technology, especialmente Copiers.
- Acompanhar faturamento, lucro e margem em conjunto, evitando decisões baseadas apenas em volume ou ticket médio.