In [1]:
# Verifica o diretório de trabalho atual para garantir que os caminhos dos arquivos estejam corretos
import os
print(os.getcwd())

d:\programação\projetospessoais\PROJETOANALISE\PROJETO\notebooks

In [2]:
# Importa a biblioteca Pandas, essencial para manipulação e análise de tabelas de dados
import pandas as pd

In [3]:
# Carrega o conjunto de dados bruto. 
# encoding='latin1' é usado porque o arquivo possui caracteres especiais (acentos, etc) que o padrão UTF-8 não reconhece
df = pd.read_csv('../dados/bruto/Sample - Superstore.csv', encoding='latin1')

In [4]:
# Exibe as primeiras 5 linhas do DataFrame para ter uma visão geral das colunas e dos dados
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [5]:
# Analisa a estrutura do DataFrame: tipos de dados, se há valores nulos e o volume de memória usado
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [6]:
# Verifica a existência de linhas idênticas para garantir que não haja contagem duplicada de vendas
print(f"Linhas duplicadas: {df.duplicated().sum()}")

Linhas duplicadas: 0

In [7]:
# Cálculo do KPI de Vendas Totais: soma de todo o faturamento da empresa
vendas=df['Sales'].sum()
print(vendas)

2297200.8603

In [8]:
# Cálculo do KPI de Lucro Total: soma de todos os lucros (positivos e negativos)
lucro_total=df['Profit'].sum()
print(lucro_total)

286397.0217

In [9]:
# Identifica as vendas que geraram prejuízo (lucro < 0) e soma esse prejuízo total
# Isso ajuda a entender a escala do problema financeiro da empresa
vendas_prejuizo=df[df['Profit'] < 0]
lucro_negativo=vendas_prejuizo['Profit'].sum()
print(lucro_negativo)

-156131.2857

In [10]:
# Agrupa os dados por Categoria para descobrir qual setor do negócio é mais lucrativo
lucro_categoria=df.groupby('Category')['Profit'].sum()
print(lucro_categoria)

Category
Furniture           18451.2728
Office Supplies    122490.8008
Technology         145454.9481
Name: Profit, dtype: float64

In [11]:
# Detalha o lucro por Subcategoria para localizar exatamente onde o dinheiro está sendo perdido
lucro_subcategorias=df.groupby('Sub-Category')['Profit'].sum()
print(lucro_subcategorias)

Sub-Category
Accessories    41936.6357
Appliances     18138.0054
Art             6527.7870
Binders        30221.7633
Bookcases      -3472.5560
Chairs         26590.1663
Copiers        55617.8249
Envelopes       6964.1767
Fasteners        949.5182
Furnishings    13059.1436
Labels          5546.2540
Machines        3384.7569
Paper          34053.5693
Phones         44515.7306
Storage        21278.8264
Supplies       -1189.0995
Tables        -17725.4811
Name: Profit, dtype: float64

In [12]:
# Ordena os lucros das subcategorias do menor para o maior
# Isso evidencia rapidamente a subcategoria 'Tables' como a principal fonte de prejuízo
lucro_ordenado=lucro_subcategorias.sort_values()
print(lucro_ordenado)

Sub-Category
Tables        -17725.4811
Bookcases      -3472.5560
Supplies       -1189.0995
Fasteners        949.5182
Machines        3384.7569
Labels          5546.2540
Art             6527.7870
Envelopes       6964.1767
Furnishings    13059.1436
Appliances     18138.0054
Storage        21278.8264
Chairs         26590.1663
Binders        30221.7633
Paper          34053.5693
Accessories    41936.6357
Phones         44515.7306
Copiers        55617.8249
Name: Profit, dtype: float64

In [13]:
# PASSO 4: INVESTIGAÇÃO DA CAUSA RAIZ
# Isolamos apenas as vendas de 'Tables' para analisar o comportamento específico desta subcategoria
tables=df[df['Sub-Category']=='Tables']
print(tables)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
3          4  US-2015-108966  10/11/2015  10/18/2015  Standard Class
10        11  CA-2014-115812    6/9/2014   6/14/2014  Standard Class
24        25  CA-2015-106320   9/25/2015   9/30/2015  Standard Class
117      118  CA-2015-110457    3/2/2015    3/6/2015  Standard Class
125      126  US-2014-134614   9/20/2014   9/25/2014  Standard Class
...      ...             ...         ...         ...             ...
9857    9858  CA-2015-164301   3/26/2015   3/30/2015  Standard Class
9899    9900  US-2014-117380   3/28/2014    4/3/2014  Standard Class
9937    9938  CA-2016-164889    6/3/2016    6/6/2016    Second Class
9955    9956  CA-2015-141593  12/14/2015  12/16/2015    Second Class
9980    9981  US-2015-151435    9/6/2015    9/9/2015    Second Class

     Customer ID    Customer Name      Segment        Country  \
3       SO-20335   Sean O'Donnell     Consumer  United States
10      BH-11710  Brosina Hoffman     Consumer  United States
24      EB-13870      Emily Burns     Consumer  United States
117     DK-13090        Dave Kipp     Consumer  United States
125     PF-19165       Philip Fox     Consumer  United States
...          ...              ...          ...            ...
9857    EB-13840    Ellis Ballard    Corporate  United States
9899    MP-18175   Mike Pelletier  Home Office  United States
9937    CP-12340   Christine Phan    Corporate  United States
9955    DB-12970      Darren Budd    Corporate  United States
9980    SW-20455      Shaun Weien     Consumer  United States

                 City  ... Postal Code   Region       Product ID   Category  \
3     Fort Lauderdale  ...       33311    South  FUR-TA-10000577  Furniture
10        Los Angeles  ...       90032     West  FUR-TA-10001539  Furniture
24               Orem  ...       84057     West  FUR-TA-10000577  Furniture
117           Seattle  ...       98103     West  FUR-TA-10001768  Furniture
125       Bloomington  ...       61701  Central  FUR-TA-10004534  Furniture
...               ...  ...         ...      ...              ...        ...
9857          Seattle  ...       98103     West  FUR-TA-10001889  Furniture
9899      Springfield  ...       45503     East  FUR-TA-10000198  Furniture
9937      Los Angeles  ...       90049     West  FUR-TA-10001676  Furniture
9955      Los Angeles  ...       90045     West  FUR-TA-10002622  Furniture
9980        Lafayette  ...       70506    South  FUR-TA-10001039  Furniture

     Sub-Category                                       Product Name  \
3          Tables      Bretford CR4500 Series Slim Rectangular Table
10         Tables           Chromcraft Rectangular Conference Tables
24         Tables      Bretford CR4500 Series Slim Rectangular Table
117        Tables                    Hon Racetrack Conference Tables
125        Tables                    Bevis 44 x 96 Conference Tables
...           ...                                                ...
9857       Tables  Bush Advantage Collection Racetrack Conference...
9899       Tables  Chromcraft Bull-Nose Wood Oval Conference Tabl...
9937       Tables       Hon 61000 Series Interactive Training Tables
9955       Tables  Bush Andora Conference Table, Maple/Graphite G...
9980       Tables                         KI Adjustable-Height Table

          Sales  Quantity  Discount    Profit
3      957.5775         5      0.45 -383.0310
10    1706.1840         9      0.20   85.3092
24    1044.6300         3      0.00  240.2649
117    787.5300         3      0.00  165.3813
125    617.7000         6      0.50 -407.6820
...         ...       ...       ...       ...
9857  3393.6800         8      0.00  610.8624
9899   330.5880         1      0.40 -143.2548
9937    71.0880         2      0.20   -1.7772
9955   273.5680         2      0.20   10.2588
9980    85.9800         1      0.00   22.3548

[319 rows x 21 columns]

In [14]:
# Filtrando vendas de mesas com descontos agressivos (20% ou mais)
# Hipótese: Descontos altos estão anulando a margem de lucro
df_high_discount=tables[tables['Discount']>=0.2]
print(df_high_discount)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
3          4  US-2015-108966  10/11/2015  10/18/2015  Standard Class
10        11  CA-2014-115812    6/9/2014   6/14/2014  Standard Class
125      126  US-2014-134614   9/20/2014   9/25/2014  Standard Class
201      202  CA-2014-133690    8/3/2014    8/5/2014     First Class
231      232  US-2017-100930    4/7/2017   4/12/2017  Standard Class
...      ...             ...         ...         ...             ...
9745    9746  CA-2017-137505  11/24/2017  11/24/2017        Same Day
9746    9747  CA-2017-137505  11/24/2017  11/24/2017        Same Day
9899    9900  US-2014-117380   3/28/2014    4/3/2014  Standard Class
9937    9938  CA-2016-164889    6/3/2016    6/6/2016    Second Class
9955    9956  CA-2015-141593  12/14/2015  12/16/2015    Second Class

     Customer ID       Customer Name      Segment        Country  \
3       SO-20335      Sean O'Donnell     Consumer  United States
10      BH-11710     Brosina Hoffman     Consumer  United States
125     PF-19165          Philip Fox     Consumer  United States
201     BS-11755       Bruce Stewart     Consumer  United States
231     CS-12400  Christopher Schild  Home Office  United States
...          ...                 ...          ...            ...
9745    BP-11290          Beth Paige     Consumer  United States
9746    BP-11290          Beth Paige     Consumer  United States
9899    MP-18175      Mike Pelletier  Home Office  United States
9937    CP-12340      Christine Phan    Corporate  United States
9955    DB-12970         Darren Budd    Corporate  United States

                 City  ... Postal Code   Region       Product ID   Category  \
3     Fort Lauderdale  ...       33311    South  FUR-TA-10000577  Furniture
10        Los Angeles  ...       90032     West  FUR-TA-10001539  Furniture
125       Bloomington  ...       61701  Central  FUR-TA-10004534  Furniture
201            Denver  ...       80219     West  FUR-TA-10004289  Furniture
231             Tampa  ...       33614    South  FUR-TA-10001705  Furniture
...               ...  ...         ...      ...              ...        ...
9745      Los Angeles  ...       90008     West  FUR-TA-10000617  Furniture
9746      Los Angeles  ...       90008     West  FUR-TA-10001676  Furniture
9899      Springfield  ...       45503     East  FUR-TA-10000198  Furniture
9937      Los Angeles  ...       90049     West  FUR-TA-10001676  Furniture
9955      Los Angeles  ...       90045     West  FUR-TA-10002622  Furniture

     Sub-Category                                       Product Name  \
3          Tables      Bretford CR4500 Series Slim Rectangular Table
10         Tables           Chromcraft Rectangular Conference Tables
125        Tables                    Bevis 44 x 96 Conference Tables
201        Tables  BoxOffice By Design Rectangular and Half-Moon ...
231        Tables   Bush Advantage Collection Round Conference Table
...           ...                                                ...
9745       Tables  Hon Practical Foundations 30 x 60 Training Tab...
9746       Tables       Hon 61000 Series Interactive Training Tables
9899       Tables  Chromcraft Bull-Nose Wood Oval Conference Tabl...
9937       Tables       Hon 61000 Series Interactive Training Tables
9955       Tables  Bush Andora Conference Table, Maple/Graphite G...

          Sales  Quantity  Discount    Profit
3      957.5775         5      0.45 -383.0310
10    1706.1840         9      0.20   85.3092
125    617.7000         6      0.50 -407.6820
201    218.7500         2      0.50 -161.8750
231    233.8600         2      0.45 -102.0480
...         ...       ...       ...       ...
9745   364.0800         2      0.20    9.1020
9746    71.0880         2      0.20   -1.7772
9899   330.5880         1      0.40 -143.2548
9937    71.0880         2      0.20   -1.7772
9955   273.5680         2      0.20   10.2588

[247 rows x 21 columns]

In [15]:
# Filtrando vendas de mesas com descontos baixos (menos de 20%)
# Serve como grupo de controle para comparar se o prejuízo persiste sem descontos altos
df_low_discount=tables[tables['Discount']<0.2]
print(df_low_discount)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
24        25  CA-2015-106320   9/25/2015   9/30/2015  Standard Class
117      118  CA-2015-110457    3/2/2015    3/6/2015  Standard Class
226      227  CA-2015-163055    8/9/2015   8/16/2015  Standard Class
522      523  CA-2017-145142   1/23/2017   1/25/2017     First Class
721      722  CA-2016-142335  12/15/2016  12/19/2016  Standard Class
...      ...             ...         ...         ...             ...
9493    9494  CA-2016-105207    1/3/2016    1/8/2016  Standard Class
9637    9638  CA-2014-124702  11/18/2014  11/25/2014  Standard Class
9756    9757  CA-2017-113705   3/27/2017   3/29/2017    Second Class
9857    9858  CA-2015-164301   3/26/2015   3/30/2015  Standard Class
9980    9981  US-2015-151435    9/6/2015    9/9/2015    Second Class

     Customer ID  Customer Name    Segment        Country          City  ...  \
24      EB-13870    Emily Burns   Consumer  United States          Orem  ...
117     DK-13090      Dave Kipp   Consumer  United States       Seattle  ...
226     DS-13180    David Smith  Corporate  United States       Detroit  ...
522     MC-17605   Matt Connell  Corporate  United States       Detroit  ...
721     MP-17965  Michael Paige  Corporate  United States       Detroit  ...
...          ...            ...        ...            ...           ...  ...
9493    BO-11350  Bill Overfelt  Corporate  United States  Broken Arrow  ...
9637    MH-17785    Maya Herman  Corporate  United States       Seattle  ...
9756    LC-16870  Lena Cacioppo   Consumer  United States      Richmond  ...
9857    EB-13840  Ellis Ballard  Corporate  United States       Seattle  ...
9980    SW-20455    Shaun Weien   Consumer  United States     Lafayette  ...

     Postal Code   Region       Product ID   Category Sub-Category  \
24         84057     West  FUR-TA-10000577  Furniture       Tables
117        98103     West  FUR-TA-10001768  Furniture       Tables
226        48227  Central  FUR-TA-10003748  Furniture       Tables
522        48234  Central  FUR-TA-10001857  Furniture       Tables
721        48205  Central  FUR-TA-10000198  Furniture       Tables
...          ...      ...              ...        ...          ...
9493       74012  Central  FUR-TA-10000617  Furniture       Tables
9637       98105     West  FUR-TA-10003008  Furniture       Tables
9756       23223    South  FUR-TA-10002533  Furniture       Tables
9857       98103     West  FUR-TA-10001889  Furniture       Tables
9980       70506    South  FUR-TA-10001039  Furniture       Tables

                                           Product Name    Sales  Quantity  \
24        Bretford CR4500 Series Slim Rectangular Table  1044.63         3
117                     Hon Racetrack Conference Tables   787.53         3
226                     Bevis 36 x 72 Conference Tables   622.45         5
522                   Balt Solid Wood Rectangular Table   210.98         2
721   Chromcraft Bull-Nose Wood Oval Conference Tabl...  1652.94         3
...                                                 ...      ...       ...
9493  Hon Practical Foundations 30 x 60 Training Tab...  1592.85         7
9637  Lesro Round Back Collection Coffee Table, End ...   730.20         4
9756                              BPI Conference Tables   292.10         2
9857  Bush Advantage Collection Racetrack Conference...  3393.68         8
9980                         KI Adjustable-Height Table    85.98         1

      Discount    Profit
24         0.0  240.2649
117        0.0  165.3813
226        0.0  136.9390
522        0.0   21.0980
721        0.0  231.4116
...        ...       ...
9493       0.0  350.4270
9637       0.0   94.9260
9756       0.0   58.4200
9857       0.0  610.8624
9980       0.0   22.3548

[72 rows x 21 columns]

In [16]:
# Calcula o lucro total para o grupo de descontos altos
# Resultado esperado: Lucro fortemente negativo
lucro_negativo=df_high_discount['Profit'].sum()
print(f"Lucro Total (Descontos >= 20%): {lucro_negativo}")

Lucro Total (Descontos >= 20%): -31001.7808

In [17]:
# Calcula o lucro total para o grupo de descontos baixos
# Resultado esperado: Lucro positivo ou prejuízo irrelevante
lucro_positivo=df_low_discount['Profit'].sum()
print(f"Lucro Total (Descontos < 20%): {lucro_positivo}")

Lucro Total (Descontos < 20%): 13276.2997

In [18]:
# LIMPEZA DE DADOS: Transformando colunas de data de texto (str) para formato datetime
# Isso permite realizar cálculos de tempo, sazonalidade e análises temporais
df['Order Date']=pd.to_datetime(df['Order Date'])
df['Ship Date']=pd.to_datetime(df['Ship Date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 3.2 MB

In [19]:
dado_nulo=df.isnull().sum()
print(dado_nulo)
df.dtypes

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code               int64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [20]:
df['dias_envio']=(df['Ship Date']-df['Order Date']).dt.days
df[['Order Date', 'Ship Date', 'dias_envio']].head()

  Order Date  Ship Date  dias_envio
0 2016-11-08 2016-11-11           3
1 2016-11-08 2016-11-11           3
2 2016-06-12 2016-06-16           4
3 2015-10-11 2015-10-18           7
4 2015-10-11 2015-10-18           7

In [21]:
analise_envio=df.groupby('dias_envio')['Profit'].agg(['count', 'sum', 'mean'])
print(analise_envio)
"""Nesta primeira análise, o prazo de envio não apresenta relação direta com prejuízo. 
Todos os prazos entre 0 e 7 dias tiveram lucro total e lucro médio positivos. 
O prazo de 4 dias concentra mais vendas, mas isso parece refletir volume operacional, não necessariamente maior rentabilidade."""

            count         sum       mean
dias_envio
0             519  15385.9685  29.645411
1             369   7541.2269  20.436929
2            1334  53118.1143  39.818676
3            1005  26875.9187  26.742208
4            2774  71134.7742  25.643394
5            2169  58733.2045  27.078471
6            1203  33275.9677  27.660821
7             621  20331.8469  32.740494

'Nesta primeira análise, o prazo de envio não apresenta relação direta com prejuízo. \nTodos os prazos entre 0 e 7 dias tiveram lucro total e lucro médio positivos. \nO prazo de 4 dias concentra mais vendas, mas isso parece refletir volume operacional, não necessariamente maior rentabilidade.'

In [22]:
calculo_margem=df['Profit']/df['Sales']
df['margem_lucro']=calculo_margem
df[['Sub-Category','Sales','Profit','margem_lucro']].head()

  Sub-Category     Sales    Profit  margem_lucro
0    Bookcases  261.9600   41.9136        0.1600
1       Chairs  731.9400  219.5820        0.3000
2       Labels   14.6200    6.8714        0.4700
3       Tables  957.5775 -383.0310       -0.4000
4      Storage   22.3680    2.5164        0.1125

In [23]:
margem_subcategoria=df.groupby('Sub-Category')['margem_lucro'].mean().sort_values()
print(margem_subcategoria)
#Na análise de margem média por venda, Binders, Appliances, Tables e Bookcases apresentam margem média negativa. 
#Porém, na análise de lucro total, Tables continua sendo o maior detrator financeiro.

Sub-Category
Binders       -0.199595
Appliances    -0.156869
Tables        -0.147727
Bookcases     -0.126640
Machines      -0.072026
Chairs         0.043900
Storage        0.089113
Supplies       0.112039
Phones         0.119222
Furnishings    0.137066
Accessories    0.218210
Art            0.251646
Fasteners      0.299171
Copiers        0.317194
Envelopes      0.423140
Paper          0.425600
Labels         0.429663
Name: margem_lucro, dtype: float64

In [24]:
resumo_subcategoria=df.groupby('Sub-Category').agg(
    total_vendas=('Sales','count'),
    lucro_total=('Profit','sum'),
    margem_media=('margem_lucro','mean')
).sort_values('lucro_total')
print(resumo_subcategoria)

              total_vendas  lucro_total  margem_media
Sub-Category
Tables                 319  -17725.4811     -0.147727
Bookcases              228   -3472.5560     -0.126640
Supplies               190   -1189.0995      0.112039
Fasteners              217     949.5182      0.299171
Machines               115    3384.7569     -0.072026
Labels                 364    5546.2540      0.429663
Art                    796    6527.7870      0.251646
Envelopes              254    6964.1767      0.423140
Furnishings            957   13059.1436      0.137066
Appliances             466   18138.0054     -0.156869
Storage                846   21278.8264      0.089113
Chairs                 617   26590.1663      0.043900
Binders               1523   30221.7633     -0.199595
Paper                 1370   34053.5693      0.425600
Accessories            775   41936.6357      0.218210
Phones                 889   44515.7306      0.119222
Copiers                 68   55617.8249      0.317194

In [25]:
#analise binders, pois foi o que mais teve margem media negativa, mas teve lucro total positivo
binders=df[df['Sub-Category']=='Binders']
binders_prejuizo=binders[binders['Profit']<0]
binders_lucro=binders[binders['Profit']>=0]

#quantidade de vendas
qt_vendas_prejuizo=len(binders_prejuizo)
qt_vendas_lucro=len(binders_lucro)

#vendas totais
vendas_totais_prejuizo=binders_prejuizo['Sales'].sum()
vendas_totais_lucro=binders_lucro['Sales'].sum()

#vendas media
vendas_media_prejuizo=binders_prejuizo['Sales'].mean()
vendas_media_lucro=binders_lucro['Sales'].mean()

#lucro total
lucro_total_prejuizo=binders_prejuizo['Profit'].sum()
lucro_total_lucro=binders_lucro['Profit'].sum()

#lucro medio
lucro_medio_prejuizo=binders_prejuizo['Profit'].mean()
lucro_medio_lucro=binders_lucro['Profit'].mean()

#margem media
margem_media_lucro=binders_lucro['margem_lucro'].mean()
margem_media_prejuizo=binders_prejuizo['margem_lucro'].mean()

#desconto medio
desc_medio_prejuizo=binders_prejuizo['Discount'].mean()
desc_medio_lucro=binders_lucro['Discount'].mean()

comparacao_binders=pd.DataFrame({
    'grupo': ['Binders com prejuizo', 'Binders com lucro'],
    'quantidade_vendas': [qt_vendas_prejuizo, qt_vendas_lucro],
    'vendas_totais': [vendas_totais_prejuizo, vendas_totais_lucro],
    'vendas_media': [vendas_media_prejuizo, vendas_media_lucro],
    'lucro_total': [lucro_total_prejuizo, lucro_total_lucro],
    'margem_media': [margem_media_prejuizo, margem_media_lucro],
    'desconto_medio': [desc_medio_prejuizo, desc_medio_lucro]
})
comparacao_binders=comparacao_binders.round(2)
print(comparacao_binders)

                  grupo  quantidade_vendas  vendas_totais  vendas_media  \
0  Binders com prejuizo                613       36140.61         58.96
1     Binders com lucro                910      167272.12        183.82

   lucro_total  margem_media  desconto_medio
0    -38510.50         -1.08            0.74
1     68732.26          0.39            0.13

In [26]:
#analise desconto binders
binders_high_discount=binders[binders['Discount'] >= 0.2]
binders_low_discount=binders[binders['Discount'] < 0.2]

print(binders_high_discount)
print(binders_low_discount)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
8          9  CA-2014-115812 2014-06-09 2014-06-14  Standard Class
13        14  CA-2016-161389 2016-12-05 2016-12-10  Standard Class
15        16  US-2015-118983 2015-11-22 2015-11-26  Standard Class
20        21  CA-2014-143336 2014-08-27 2014-09-01    Second Class
25        26  CA-2016-121755 2016-01-16 2016-01-20    Second Class
...      ...             ...        ...        ...             ...
9930    9931  CA-2015-104948 2015-11-13 2015-11-17  Standard Class
9952    9953  CA-2015-141593 2015-12-14 2015-12-16    Second Class
9954    9955  CA-2015-141593 2015-12-14 2015-12-16    Second Class
9978    9979  US-2016-103674 2016-12-06 2016-12-10  Standard Class
9979    9980  US-2016-103674 2016-12-06 2016-12-10  Standard Class

     Customer ID       Customer Name      Segment        Country  \
8       BH-11710     Brosina Hoffman     Consumer  United States
13      IM-15070        Irene Maddox     Consumer  United States
15      HP-14815       Harold Pawlan  Home Office  United States
20      ZD-21925  Zuschuss Donatelli     Consumer  United States
25      EH-13945       Eric Hoffmann     Consumer  United States
...          ...                 ...          ...            ...
9930    KH-16510       Keith Herrera     Consumer  United States
9952    DB-12970         Darren Budd    Corporate  United States
9954    DB-12970         Darren Budd    Corporate  United States
9978    AP-10720          Anne Pryor  Home Office  United States
9979    AP-10720          Anne Pryor  Home Office  United States

                City  ...       Product ID         Category Sub-Category  \
8        Los Angeles  ...  OFF-BI-10003910  Office Supplies      Binders
13           Seattle  ...  OFF-BI-10003656  Office Supplies      Binders
15        Fort Worth  ...  OFF-BI-10000756  Office Supplies      Binders
20     San Francisco  ...  OFF-BI-10002215  Office Supplies      Binders
25       Los Angeles  ...  OFF-BI-10001634  Office Supplies      Binders
...              ...  ...              ...              ...          ...
9930  San Bernardino  ...  OFF-BI-10001267  Office Supplies      Binders
9952     Los Angeles  ...  OFF-BI-10001153  Office Supplies      Binders
9954     Los Angeles  ...  OFF-BI-10000948  Office Supplies      Binders
9978     Los Angeles  ...  OFF-BI-10003727  Office Supplies      Binders
9979     Los Angeles  ...  OFF-BI-10002026  Office Supplies      Binders

                                           Product Name    Sales Quantity  \
8     DXL Angle-View Binders with Locking Rings by S...   18.504        3
13          Fellowes PB200 Plastic Comb Binding Machine  407.976        3
15     Storex DuraTech Recycled Plastic Frosted Binders    2.544        3
20          Wilson Jones Hanging View Binder, White, 1"   22.720        4
25                      Wilson Jones Active Use Binders   11.648        2
...                                                 ...      ...      ...
9930  Universal Recycled Hanging Pressboard Report B...    9.872        2
9952               Ibico Recycled Grain-Textured Covers   55.264        2
9954  GBC Laser Imprintable Binding System Covers, D...   34.248        3
9978  Avery Durable Slant Ring Binders With Label Ho...   13.376        4
9979                  Ibico Recycled Linen-Style Covers  437.472       14

     Discount    Profit  dias_envio  margem_lucro
8         0.2    5.7825           5        0.3125
13        0.2  132.5922           5        0.3250
15        0.8   -3.8160           4       -1.5000
20        0.2    7.3840           5        0.3250
25        0.2    4.2224           4        0.3625
...       ...       ...         ...           ...
9930      0.2    3.4552           4        0.3500
9952      0.2   20.7240           2        0.3750
9954      0.2   11.5587           2        0.3375
9978      0.2    4.6816           4        0.3500
9979      0.2  153.1152           4        0.3500

[1186 rows x 23 columns]
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
45        46  CA-2016-118255 2016-03-11 2016-03-13     First Class
49        50  CA-2015-115742 2015-04-18 2015-04-22  Standard Class
80        81  CA-2016-127208 2016-06-12 2016-06-15     First Class
94        95  CA-2015-149587 2015-01-31 2015-02-05    Second Class
112      113  CA-2016-128867 2016-11-03 2016-11-10  Standard Class
...      ...             ...        ...        ...             ...
9936    9937  CA-2017-132955 2017-06-24 2017-06-28  Standard Class
9951    9952  CA-2017-121559 2017-06-01 2017-06-03    Second Class
9967    9968  CA-2017-153871 2017-12-11 2017-12-17  Standard Class
9968    9969  CA-2017-153871 2017-12-11 2017-12-17  Standard Class
9970    9971  CA-2015-103772 2015-06-28 2015-07-02  Standard Class

     Customer ID       Customer Name      Segment        Country  \
45      ON-18715       Odella Nelson    Corporate  United States
49      DP-13000       Darren Powers     Consumer  United States
80      SC-20770  Stewart Carmichael    Corporate  United States
94      KB-16315          Karl Braun     Consumer  United States
112     CL-12565         Clay Ludtke     Consumer  United States
...          ...                 ...          ...            ...
9936    SC-20575        Sonia Cooley     Consumer  United States
9951    HW-14935     Helen Wasserman    Corporate  United States
9967    RB-19435     Richard Bierner     Consumer  United States
9968    RB-19435     Richard Bierner     Consumer  United States
9970    MP-17470         Mark Packer  Home Office  United States

              City  ...       Product ID         Category Sub-Category  \
45           Eagan  ...  OFF-BI-10003291  Office Supplies      Binders
49      New Albany  ...  OFF-BI-10004410  Office Supplies      Binders
80         Decatur  ...  OFF-BI-10002309  Office Supplies      Binders
94     Minneapolis  ...  OFF-BI-10002852  Office Supplies      Binders
112      Urbandale  ...  OFF-BI-10003981  Office Supplies      Binders
...            ...  ...              ...              ...          ...
9936      Cranston  ...  OFF-BI-10002735  Office Supplies      Binders
9951  Indianapolis  ...  OFF-BI-10002072  Office Supplies      Binders
9967    Plainfield  ...  OFF-BI-10004209  Office Supplies      Binders
9968    Plainfield  ...  OFF-BI-10004600  Office Supplies      Binders
9970        Smyrna  ...  OFF-BI-10002867  Office Supplies      Binders

                                           Product Name   Sales Quantity  \
45    Wilson Jones Leather-Like Binders with DublLoc...   17.46        2
49    C-Line Peel & Stick Add-On Filing Pockets, 8-3...   38.22        6
80      Avery Heavy-Duty EZD  Binder With Locking Rings   16.74        3
94                    Ibico Standard Transparent Covers   32.96        2
112                    Avery Durable Plastic 1" Binders   27.24        6
...                                                 ...     ...      ...
9936                   GBC Prestige Therm-A-Bind Covers  102.93        3
9951                      Cardinal Slant-D Ring Binders   17.38        2
9967            Fellowes Twister Kit, Gray/Clear, 3/pkg   40.20        5
9968          Ibico Ibimaster 300 Manual Binding System  735.98        2
9970            GBC Recycled Regency Composition Covers  119.56        2

     Discount    Profit  dias_envio  margem_lucro
45        0.0    8.2062           2          0.47
49        0.0   17.9634           4          0.47
80        0.0    8.0352           3          0.48
94        0.0   16.1504           5          0.49
112       0.0   13.3476           7          0.49
...       ...       ...         ...           ...
9936      0.0   48.3771           4          0.47
9951      0.0    8.6900           2          0.50
9967      0.0   18.0900           6          0.45
9968      0.0  331.1910           6          0.45
9970      0.0   54.9976           4          0.46

[337 rows x 23 columns]

In [27]:
#analise de lucro dos descontos
lucro_high_discount=binders_high_discount['Profit'].sum()
print('Lucro de desconto >=20%:', lucro_high_discount)

lucro_low_discount=binders_low_discount['Profit'].sum()
print('Lucro de desconto <20%:', lucro_low_discount)

Lucro de desconto >=20%: -9092.687399999999
Lucro de desconto <20%: 39314.4507

In [28]:
#analise de margem media de desconto
margem_high_discount=binders_high_discount['margem_lucro'].mean()
print('margem de lucro com desconto alto:', margem_high_discount)

margem_low_discount=binders_low_discount['margem_lucro'].mean()
print('margem de lucro com desconto baixo', margem_low_discount)

margem de lucro com desconto alto: -0.3913856098931984
margem de lucro com desconto baixo 0.4753709198813057

In [29]:
#analise de tables por prejuizo e lucro Profit
tables=df[df['Sub-Category'] == 'Tables']
tables_prejuizo=tables[tables['Profit']<0]
tables_lucro=tables[tables['Profit']>=0]

#quantidade de vendas
qt_vendas_prejuizo_tables=len(tables_prejuizo)
qt_vendas_lucro_tables=len(tables_lucro)

#vendas totais
vendas_totais_prejuizo_tables=tables_prejuizo['Sales'].sum()
vendas_totais_lucro_tables=tables_lucro['Sales'].sum()

#valor medio de venda
vendas_media_prejuizo_tables=tables_prejuizo['Sales'].mean()
vendas_media_lucro_tables=tables_lucro['Sales'].mean()

#lucro total
lucro_total_prejuizo_tables=tables_prejuizo['Profit'].sum()
lucro_total_lucro_tables=tables_lucro['Profit'].sum()

#margem media
margem_media_prejuizo_tables=tables_prejuizo['margem_lucro'].mean()
margem_media_lucro_tables=tables_lucro['margem_lucro'].mean()

#desconto medio
desc_medio_prejuizo_tables=tables_prejuizo['Discount'].mean()
desc_medio_lucro_tables=tables_lucro['Discount'].mean()

comparacao_tables=pd.DataFrame({
    'grupo':['tables com prejuizo', 'tables com lucro'],
    'quantidade_vendas':[qt_vendas_prejuizo_tables, qt_vendas_lucro_tables],
    'vendas_totais':[vendas_totais_prejuizo_tables, vendas_totais_lucro_tables],
    'vendas_media':[vendas_media_prejuizo_tables, vendas_media_lucro_tables],
    'lucro_total':[lucro_total_prejuizo_tables, lucro_total_lucro_tables],
    'margem_media':[margem_media_prejuizo_tables, margem_media_lucro_tables],
    'desconto_medio':[desc_medio_prejuizo_tables, desc_medio_lucro_tables]
})
comparacao_tables=comparacao_tables.round(2)
comparacao_tables

,grupo,quantidade_vendas,vendas_totais,vendas_media,lucro_total,margem_media,desconto_medio
0,tables com prejuizo,203,104978.55,517.14,-32412.15,-0.31,0.37
1,tables com lucro,116,101986.99,879.20,14686.67,0.14,0.08

In [30]:
comparacao_tables_binders=pd.concat(
    [comparacao_tables, comparacao_binders],
    ignore_index=True
)

comparacao_tables_binders.sort_values('lucro_total')
#Binders com prejuízo perde mais que Tables com prejuízo, mas ela não mostra claramente que Binders com lucro compensa isso. 
#Ou seja tables da um estrago maior no final

,grupo,quantidade_vendas,vendas_totais,vendas_media,lucro_total,margem_media,desconto_medio
2,Binders com prejuizo,613,36140.61,58.96,-38510.50,-1.08,0.74
0,tables com prejuizo,203,104978.55,517.14,-32412.15,-0.31,0.37
1,tables com lucro,116,101986.99,879.20,14686.67,0.14,0.08
3,Binders com lucro,910,167272.12,183.82,68732.26,0.39,0.13

In [37]:
comparacao_final_subcategoria=pd.DataFrame({
    'subcategoria':['Tables','Binders'],
    'lucro_grupo_prejuizo':[lucro_total_prejuizo_tables, lucro_total_prejuizo],
    'lucro_grupo_lucro':[lucro_total_lucro_tables, lucro_total_lucro],
    'lucro_total_subcategoria':[tables['Profit'].sum(), binders['Profit'].sum()],
    'margem_media_subcategoria':[tables['margem_lucro'].mean(), binders['margem_lucro'].mean()],
    'desconto_medio_prejuizo':[desc_medio_prejuizo_tables, desc_medio_prejuizo],
    'status_final':['fecha com prejuizo', 'fecha com lucro']
    
})
comparacao_final_subcategoria.round(2)

,subcategoria,lucro_grupo_prejuizo,lucro_grupo_lucro,lucro_total_subcategoria,margem_media_subcategoria,desconto_medio_prejuizo,status_final
0,Tables,-32412.15,14686.67,-17725.48,-0.15,0.37,fecha com prejuizo
1,Binders,-38510.50,68732.26,30221.76,-0.20,0.74,fecha com lucro